### PR TITLE
[DataLoader2] Deep copy DataPipe during initialization

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #786

Deep copy DataPipe during initialization to avoid sharing states if the same DataPipe is being passed to multiple usages.

This can be merged before or after #746 (the other PR will have to rebase).

Differential Revision: [D39741743](https://our.internmc.facebook.com/intern/diff/D39741743)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39741672).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39741743).

**Review by ejguan — APPROVED** [review]

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39741743).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39741743).

**Comment by ejguan** [comment]
@NivekT Do you think we need to add BC breaking note to this PR?

**Comment by NivekT** [comment]
> @NivekT Do you think we need to add BC breaking note to this PR?

Actually yes, I think we should, even though I don't think users would intentionally rely on the state of DataPipes being shared among DataLoaders.

**Comment by ejguan** [comment]
> > @NivekT Do you think we need to add BC breaking note to this PR?
> 
> Actually yes, I think we should, even though I don't think users would intentionally rely on the state of DataPipes being shared among DataLoaders.

Can you add a brief example in the bc breaking note that the same DataPipe used by multiple DLv2?

**Comment by NivekT** [comment]
Will do by the afternoon.

**Comment by ejguan** [comment]
> Will do by the afternoon.

Thank you so much!

**Comment by NivekT** [comment]
@ejguan Updated this PR's description.

**Pull request closed without merging**
