### PR TITLE
[Core] Moving Queues, Protocols and Evenloops from PyTorch core.

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #544

Adding PrototypeMultiProcessingReadingService as a candidate to replace MultiProcessingReadingService and remote DLv1 dependency

Differential Revision: [D37467653](https://our.internmc.facebook.com/intern/diff/D37467653)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
`communication` folder is 1:1 copy from pytorch/torch repo

**Review by NivekT — APPROVED** [review]
We'll need more tests over time but moving it into `TorchData` SGTM!

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37467653).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37467653).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37467653).

**Pull request closed without merging**
