### PR TITLE
Add labels to trigger slow tests and period tests

### LINKED ISSUE #33: Add label to trigger slowTest on CI
per title

### PR DESCRIPTION
**Pull request by ejguan**
Fixes #33

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #74

Differential Revision: [D31797764](https://our.internmc.facebook.com/intern/diff/D31797764)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Comment by ejguan** [comment]
Convert it draft because I have to re-attach the label to trigger the slow tests. This should be able to be fixed to add it to matrix.

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797764).

**Review by NivekT — APPROVED** [review]
LGTM

**Pull request closed without merging**
