### PR TITLE
Ensuring DataFrame DataPipes are serializable

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #276
* #275

`torcharrow.dtypes.Struct` requires `dill` to serialize

Differential Revision: [D34625706](https://our.internmc.facebook.com/intern/diff/D34625706)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34625706).

**Comment by NivekT** [comment]
@wenleix confirmed that we can use `dill` to serialize for now because there is a `namedtuple` in there. The `dtypes.Struct` might become pickable at a later point.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34625706).

**Comment by wenleix** [comment]
Working on make TorchArrow Dtype pickable .

**Pull request closed without merging**
