### PR TITLE
Switching to use FileOpener instead of FileLoader

### LINKED ISSUE #103: Switch `FileLoader` to `FileOpener`
Should we change the name of `FileLoader` to `FileOpener`?

We split the file-loading functionality into three steps:
- List file names in a directory: `FileLister`
- Open file handles: `FileLoader` (I personally feel like the name is incorrect.)
- Read files: `dp.map(fn=lambda x: x.read(), input_col=1)`

cc: @VitalyFedyunin @NivekT

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #151
* __->__ #148

This PR is dependent on https://github.com/pytorch/pytorch/pull/70367, which renames `FileLoader` to `FileOpener` in PyTorch. Core library. Then, this PR switches all `TorchData` usage of `FileLoader` to `FileOpener`. Downstream users need to be aware of this.

Fixes #103.

cc: @ejguan @VitalyFedyunin @pmeier @Nayef211

Differential Revision: [D33368187](https://our.internmc.facebook.com/intern/diff/D33368187)

### CODE REVIEW

**Comment by NivekT** [comment]
Note that, since pytorch/pytorch#70367 has not landed, the CI tests here are expected to fail.

**Review by ejguan — APPROVED** [review]
LGTM as long as all tests passed. Please also inform vision and text team for this change.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368187).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368187).

**Pull request closed without merging**
