### PR TITLE
[DataPipe] Implement `pause`/`resume` for FullSync

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #1130

Differential Revision: [D45015591](https://our.internmc.facebook.com/intern/diff/D45015591)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45015591).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45015591).

**Review by ejguan — APPROVED** [review]
As long as the implementation doesn't invalidate the `timeout` from FullSync (if not all of ranks have received data at the same iteration), it should be good. Stamping on it and pls test it with the removing delegation PR.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45015591).

**Pull request closed without merging**
