### PR TITLE
Small fix to functional name and usage example

### LINKED ISSUE #433: HashChecker example is broken
https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/torchdata/datapipes/iter/util/hashchecker.py#L36-L48

Running this will raise a `StopIteration`. The reason is simple: we want to read from a stream that was already exhausted by the hash checking. The docstring tells us that much

https://github.com/pytorch/data/blob/6a8415b1ced33e5653f7a38c93f767ac8e1c7e79/torchdata/datapipes/iter/util/hashchecker.py#L32-L33

and we correctly set `rewind=False`.

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #440

Fixes #433

Differential Revision: [D36601420](https://our.internmc.facebook.com/intern/diff/D36601420)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36601420).

**Review by ejguan — COMMENTED** [review]
Could we fix [this](https://github.com/pytorch/data/issues/433) as well?

**Review by ejguan — APPROVED** [review]
LGTM.

**Comment by NivekT** [comment]
> Could we fix [this](https://github.com/pytorch/data/issues/433) as well?

I think this PR does fix that as well. Am I missing something?

**Comment by ejguan** [comment]
Could you please also add a PR cherrypick it to the release branch? Thank you

**Pull request closed without merging**
