### PR TITLE
Refactor IoPath FileLister and FileLoader

### LINKED ISSUE #52: Use IoPath to download HTTP Url
Since IoPath has features to download different sources: HTTP, S3, Google, and etc, we should add a `IoPathDownloader` to handle all different sources.

### PR DESCRIPTION
**Pull request by ejguan**
Fixes #52

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #105 Add IoPathSaver and unify the mode for Saver
* **#104 Refactor IoPath FileLister and FileLoader**

This PR is going to add all existing PathHandlers from iopath to make sure it can handle the following data sources:
- Local File Path
- HTTP Url
- OneDrive Url
- S3 Url (iopath 0.1.9)

Before this PR, these two DataPipes only work with NativePathHandler, which would handle the local file.

Differential Revision: [D32317605](https://our.internmc.facebook.com/intern/diff/D32317605)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32317605).

**Review by NivekT — APPROVED** [review]
LGTM! Previously reviewed on an old PR.

**Comment by NivekT** [comment]
Nit: we may have to change `IoPathFileLoader` to `IoPathFileOpener` later but it seems good to me for now.

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D32317605).

**Pull request closed without merging**
