### PR TITLE
Adding ability to redefine cache timeout

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #571

Differential Revision: [D37723437](https://our.internmc.facebook.com/intern/diff/D37723437)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@parmeet can you please review this code (@ejguan and @NivekT are on PTO)

**Comment by VitalyFedyunin** [comment]
IMO DLv2 should apply adapter modifications once on the local copy of the graph it gets from the args.

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37723437).

**Review by NivekT — APPROVED** [review]

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37723437).

**Review by parmeet — APPROVED** [review]
LGTM! Thanks @VitalyFedyunin for adding the ability to manually set time for caching files. Just to be sure, the users can add this adapter on top of datapipe we return for datasets, in other words, we do not have to add this adapter internally in the dataset implementation right?

**Comment by VitalyFedyunin** [comment]
> LGTM! Thanks @VitalyFedyunin for adding the ability to manually set time for caching files. Just to be sure, the users can add this adapter on top of datapipe we return for datasets, in other words, we do not have to add this adapter internally in the dataset implementation right?

Correct

**Pull request closed without merging**
