### PR TITLE
Rename BucketBatcher argument to avoid name collision

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #304
* #290

We have a DataPipe using the functional API name `in_batch_shuffle`. Therefore, this DataPipe should **not** have a class variable with the same name to avoid confusion.

Differential Revision: [D34939045](https://our.internmc.facebook.com/intern/diff/D34939045)

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
Thanks for fixing it.
I was also thinking to change the name of this DataPipe to `Bucketizer` with functional name `bucketize` in favor of this commonly used name (https://www.tensorflow.org/tfx/transform/api_docs/python/tft/bucketize)

**Comment by NivekT** [comment]
> Thanks for fixing it. I was also thinking to change the name of this DataPipe to `Bucketizer` with functional name `bucketize` in favor of this commonly used name (https://www.tensorflow.org/tfx/transform/api_docs/python/tft/bucketize)

I think that seems reasonable. We will have to go through the deprecation process.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34939045).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34939045).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D34939045).

**Pull request closed without merging**
