### PR TITLE
[DataLoader2] Moving a few tests from Core to TorchData

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #892

These tests are removed from Core in https://github.com/pytorch/pytorch/pull/88848

Differential Revision: [D41204079](https://our.internmc.facebook.com/intern/diff/D41204079)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41202830).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41204079).

**Review by ejguan — APPROVED** [review]
LGTM thanks

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41204079).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D41204079).

**Pull request closed without merging**
