### PR TITLE
Improve graph visualization documentation

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #505
* __->__ #504

Improve docstring, added an example, and expanded documentation to have a template for utility functions (not just class)

If there isn't strong objection, I plan to cherry-pick this and the graph visualization PR to release 0.4.0 (cc: @ejguan).

Differential Revision: [D37040783](https://our.internmc.facebook.com/intern/diff/D37040783)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
How you manage to import part of the stack? =)

**Review by ejguan — APPROVED** [review]
LGTM, and I am fine to cherry pick the graph visualization PRs to the release.

I am still a noob regarding these rst files. Could you please provide a reference of rendered page?

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37040783).

**Comment by NivekT** [comment]
> LGTM, and I am fine to cherry pick the graph visualization PRs to the release.
> 
> I am still a noob regarding these rst files. Could you please provide a reference of rendered page?

Here you go:

Screen Shot 2022-06-09 at 1 23 35 PM

Screen Shot 2022-06-09 at 1 23 21 PM

**Comment by ejguan** [comment]
Thank you! Looks great.

**Pull request closed without merging**
