### PR TITLE
Fixing interface generation issue

### LINKED ISSUE #343: [Codegen] gen_pyi would change directory that leads to wrong directory to generate wheel
### 🐛 Describe the bug

This is the follow up of #344

If we move `gen_pyi` before `setup` function, we would encounter a problem that the working directory is moved to `torchdata/datapipes` due to the code in PyTorch Core.

https://github.com/pytorch/pytorch/blob/ea2e0e773b6c043f0e17962c5a236b9f87241761/torch/utils/data/datapipes/gen_pyi.py#L173-L176

I have to change directory back to the root if I run `gen_pyi`

### Versions

main branch

cc: @NivekT

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #357

This needs to wait until https://github.com/pytorch/pytorch/pull/75602 lands

Fixes #343

Differential Revision: [D35578969](https://our.internmc.facebook.com/intern/diff/D35578969)

### CODE REVIEW

**Review by ejguan — APPROVED** [review]
Thanks, LGTM.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35578969).

**Comment by NivekT** [comment]
Looks like the installation is falling for Python 3.8 (even with "develop" changed to "install"), I am not sure what is causing the issue but we can wait for another PyTorch nightly release to come out and see if it persists.

**Comment by ejguan** [comment]
FYI, my PR just opened seems not failing on macos python 3.8.

**Comment by NivekT** [comment]
The CIs that were failing are now fine. I will be landing this.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35578969).

**Pull request closed without merging**
