### PR TITLE
Add DL tests to Text examples & Add lambda fn warning to cache

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#168 Add DL tests to Text examples & Add lambda fn warning to cache**

This PR needs to wait until https://github.com/pytorch/pytorch/pull/71311 is landed.

Differential Revision: [D33589170](https://our.internmc.facebook.com/intern/diff/D33589170)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33589170).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33589170).

**Comment by ejguan** [comment]
The root cause of CI failures in macos and windows is the nightly of PyTorch Core on these two systems have not been updated for a week

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33589170).

**Review by NivekT — APPROVED** [review]
LGTM! Thanks for adding this!

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33589170).

**Pull request closed without merging**
