### PR TITLE
Daemonize reading service's processes

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #824
* __->__ #823

fixes: #806

Differential Revision: [D40280665](https://our.internmc.facebook.com/intern/diff/D40280665)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40280665).

**Review by NivekT — COMMENTED** [review]
I just tried this locally. It does terminate but it returns the following error:

```python
Exception ignored in: <function DataLoader2.__del__ at 0x7f96eb666820>
Traceback (most recent call last):
  File "/Users//data/torchdata/dataloader2/dataloader2.py", line 134, in __del__
  File "/Users//data/torchdata/dataloader2/dataloader2.py", line 142, in shutdown
  File "/Users//data/torchdata/dataloader2/reading_service.py", line 296, in finalize
  File "/Users//data/torchdata/dataloader2/reading_service.py", line 291, in clean_me
AttributeError: 'NoneType' object has no attribute 'TerminateRequest'
Exception ignored in: <function PrototypeMultiProcessingReadingService.__del__ at 0x7f96eb668af0>
Traceback (most recent call last):
  File "/Users//data/torchdata/dataloader2/reading_service.py", line 284, in __del__
  File "/Users//data/torchdata/dataloader2/reading_service.py", line 296, in finalize
  File "/Users//data/torchdata/dataloader2/reading_service.py", line 291, in clean_me
AttributeError: 'NoneType' object has no attribute 'TerminateRequest'
```

**Comment by ejguan** [comment]
> I just tried this locally. It does terminate but it returns the following error:
> 
> ```
> Exception ignored in: <function DataLoader2.__del__ at 0x7f96eb666820>
> Traceback (most recent call last):
>   File "/Users//data/torchdata/dataloader2/dataloader2.py", line 134, in __del__
>   File "/Users//data/torchdata/dataloader2/dataloader2.py", line 142, in shutdown
>   File "/Users//data/torchdata/dataloader2/reading_service.py", line 296, in finalize
>   File "/Users//data/torchdata/dataloader2/reading_service.py", line 291, in clean_me
> AttributeError: 'NoneType' object has no attribute 'TerminateRequest'
> Exception ignored in: <function PrototypeMultiProcessingReadingService.__del__ at 0x7f96eb668af0>
> Traceback (most recent call last):
>   File "/Users//data/torchdata/dataloader2/reading_service.py", line 284, in __del__
>   File "/Users//data/torchdata/dataloader2/reading_service.py", line 296, in finalize
>   File "/Users//data/torchdata/dataloader2/reading_service.py", line 291, in clean_me
> AttributeError: 'NoneType' object has no attribute 'TerminateRequest'
> ```

This is the common problem that `Python` has already exited before `__del__` is invoked. We can simply check if those variables/modules are None. If `None`, we can skip `cleanup` and return directly.

**Comment by VitalyFedyunin** [comment]
That's one of the options. Also requires join timeouts and errors propagation.

**Review by NivekT — COMMENTED** [review]
@VitalyFedyunin 

I just quickly tested that if we define `finalize` of PrototypeRS to catch the `None` cases, it should work:

```python
def finalize(self) -> None:
    r"""
    ``MultiProcessingReadingService`` invalidate states & properly exits all subprocesses.
    """
    # TODO(618): Check if anyone stuck with messages
    def clean_me(process, req_queue, res_queue):
        # TODO(619): Can send terminations simultaneously
        # TODO(620): Make termination a function of QueueWrapperDataPipe (similar to reset)
        try:
            req_queue.put(communication.messages.TerminateRequest())
            _ = res_queue.get()
        # Due to non-deterministic order of destruction, by the time `finalize` is called,
        # some objects may already be `None`.
        except AttributeError:
            pass
        process.join()

    for process, req_queue, res_queue in self.processes:
        clean_me(process, req_queue, res_queue)

    self.processes = []
```

**Comment by NivekT** [comment]
This can be closed as #837 has landed

**Pull request closed without merging**
