### PR TITLE
3.11 Conda for Mac/Windows

### PR DESCRIPTION
**Pull request by osalpekar**

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Comment by ejguan** [comment]
I think I need to revert this PR and re-land it from Phabricator. Otherwise, Github and internal codebase would diverge.

**Comment by ejguan** [comment]
I am not sure how this PR got merged. The main branch should be protected.

cc: @malfet

**Comment by ejguan** [comment]
I am not sure which one is the better option to make two repose in sync:
- Revert and merge to main branch
- **force** push to main branch to remove this commit

Let me know what do you think @osalpekar @malfet

**Comment by malfet** [comment]
@ejguan sorry about that, for some reason FaceHub didn't show "Import to Phabricator" button, so I've merged it.
@osalpekar let's redo the PR and follow standard approval process.

**Comment by ejguan** [comment]
> @ejguan sorry about that, for some reason FaceHub didn't show "Import to Phabricator" button, so I've merged it.

No problem. I guess you have the premium permission to merge PRs~ 😃

> On the bright side, we have 3.11 conda packages for all OSes in https://anaconda.org/pytorch-nightly/torchdata/files so we can test if text is buildable today.

It's awesome. And, we will start to do branch cut today. Pls let us know if it's working properly with Text. If not, we can disable 3.11 in the release branch.

QQ: Are we expected to support 3.11 for the coming release? I thought it wasn't one goal during the discussion in release meeting.

**Comment by osalpekar** [comment]
Whoops didn't know we're using doing Phabricator-based landing here! Thanks @ejguan and @NivekT for getting this relanded quickly!

**Pull request merged**
