### PR TITLE
Fix ArchiveReader to keep archive path

### PR DESCRIPTION
**Pull request by ejguan**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #74
* __->__ #73
* #72

Previous implementation of `ArchiveReader` has a bug. Please take a reference from https://github.com/pytorch/pytorch/pull/65424#issuecomment-945479647

cc: @Nayef211

Differential Revision: [D31797765](https://our.internmc.facebook.com/intern/diff/D31797765)

### CODE REVIEW

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797765).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797765).

**Comment by ejguan** [comment]
@ejguan has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D31797765).

**Review by NivekT — APPROVED** [review]
LGTM

**Pull request closed without merging**
