### PR TITLE
[WIP] pin_memory DataPipe and adapter

### PR DESCRIPTION
**Pull request by VitalyFedyunin**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #485
* #484

Differential Revision: [D36866290](https://our.internmc.facebook.com/intern/diff/D36866290)

### CODE REVIEW

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36866290).

**Comment by VitalyFedyunin** [comment]
@VitalyFedyunin has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36866290).

**Comment by VitalyFedyunin** [comment]
Looks like pin_memory should be a parameter of ReadingService, otherwise 'pin' gets lost when tensors are moved from child processes to the main training loop.

CC @ejguan

**Comment by ejguan** [comment]
> Looks like pin_memory should be a parameter of ReadingService, otherwise 'pin' gets lost when tensors are moved from child processes to the main training loop.
> 
> CC @ejguan

Do we want to have special DataPipes that can only be iterated on main process (cannot moved to child process)? If so, we might still keep it as an Adapter and use a special DataPipe. FWIW, we might need such feature for DataPipe operations when Tensor is pinned or sent to cuda.

**Comment by VitalyFedyunin** [comment]
Makes total sense to me, I will update MPReadingService to respect such DataPipes as part of this PR.

**Pull request closed without merging**
