### PR TITLE
fix lint error for `load_state_dict` API 

### PR DESCRIPTION
**Pull request by ninginthecloud**
Please read through our [contribution guide](https://github.com/pytorch/data/blob/main/CONTRIBUTING.md) prior to
creating your pull request.

- Note that there is a section on requirements related to adding a new DataPipe.

Fixes  lint errors in previous `load_state_dict` API  [commit](https://github.com/pytorch/data/commit/02157d825af9a31b0f782a9b2a9d504c59a28280) 

### Changes

- update based on ```pre-commit run --files torchdata/dataloader2/dataloader2.py```

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
It seems the Lint for dataloader2.py is not fixed. Could you please run `pre-commit run --files`?

**Comment by ninginthecloud** [comment]
> It seems the Lint for dataloader2.py is not fixed. Could you please run `pre-commit run --files`?

It seems like we can't run `pre-commit run --files` without a commit hook. I pushed my local change to remote now.

**Review by ejguan — APPROVED** [review]
LGTM. Thank you! You can import this PR to Phabricator and land it from internal side.

**Comment by ninginthecloud** [comment]
> LGTM. Thank you! You can import this PR to Phabricator and land it from internal side.

Thank you! This flow is interesting! Let me give a try.

**Pull request closed without merging**
