### PR TITLE
azureml datastore example

### PR DESCRIPTION
**Pull request by samuel100**
### Changes

- added a section to the tutorial documentation on Accessing Azure ML Datastores with `fsspec` DataPipes.

Fixes #946

### CODE REVIEW

**Review by ejguan — COMMENTED** [review]
Thank you for taking interest in contributing torchdata. We do need you to have CLA signed to land any code.

**Comment by NivekT** [comment]
I built the doc locally and it looks great to me. Thank you so much for contributing this PR.

Please sign the CLA and I will get this landed!

---


Not directly related to this PR (more like a note to myself), for some reasons I noticed, the right sidebar of the [tutorial on the `main` branch](https://pytorch.org/data/main/tutorial.html) is missing the [+] expansion that is rendered properly locally:

Screenshot 2023-01-17 at 3 28 18 PM

It is working locally:

Screenshot 2023-01-17 at 3 28 30 PM

We should check to see if it shows up as normal after this PR lands.

**Review by NivekT — APPROVED** [review]

**Comment by NivekT** [comment]
Hey @samuel100, let us know when you have the chance to sign the CLA. Thanks!

**Review by NivekT — APPROVED** [review]
@samuel100 Hi, just pinging again as we would like to include this PR in our next release. 
Please sign the CLA and rebase the branch. Thank you!

**Comment by samuel100** [comment]
@NivekT I have just signed the CLA. Would it be possible to merge this in now? Many thanks for your patience.

**Review by NivekT — APPROVED** [review]

**Pull request closed without merging**
