### PR TITLE
Updating test code to follow single iterator constraint

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #388
* __->__ #386

This should be landed after https://github.com/pytorch/pytorch/pull/75995

Note that the CI is expected to fail until that PR goes into nightly

Differential Revision: [D36182556](https://our.internmc.facebook.com/intern/diff/D36182556)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36182556).

**Review by ejguan — APPROVED** [review]

**Comment by NivekT** [comment]
Yea, but the issue with GHA is that even though nightly has landed, the internal diff hasn't, and my diff (D36182556) is dependent on the internal one landing first.

The options are:
1. Remove the dependencies from D36182556 and land this (it won't pass the internal test, because the other stack hasn't landed yet)
2. Wait for the other stack of diffs to land, then land this one (D36182556)

**Comment by ejguan** [comment]
Oh. I don't realize such problem, good to know. Let's wait until internal Diff landed. (Decoupling is more important now)

**Comment by ejguan** [comment]
If the whole stack of PRs got reverted because the failed internal tests for TorchData, you might need to combine this PR with the PR in PyTorch core in a single Diff and land it from internal Phabricator.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D36182556).

**Pull request closed without merging**
