### PR TITLE
Refactor to use `traverse_dps` instead of `traverse`

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #793

This should be merged only after https://github.com/pytorch/pytorch/pull/85667 has been merged into nightly and internal.

Differential Revision: [D39860692](https://our.internmc.facebook.com/intern/diff/D39860692)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39860692).

**Review by ejguan — APPROVED** [review]
LGTM. Let's wait until the nightly is updated. And, we can't land this PR right now since the PyTorch core Diff has not been merged yet.

**Comment by NivekT** [comment]
There is a circular import issue. Let me have a look tomorrow.

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39860692).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39860692).

**Pull request closed without merging**
