### PR TITLE
Renaming IoPathFileLoader to IoPathFileOpener

### PR DESCRIPTION
**Pull request by NivekT**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #151
* #148

Previously, this was one PR, but now we are breaking it into two parts.

Renaming `IoPathFileLoader` to `IoPathFileOpener` (the functional name changes as well). Downstream users of those DataPipes please be aware of that.

Part of #103

cc: @ejguan @VitalyFedyunin @pmeier @Nayef211

Differential Revision: [D33368186](https://our.internmc.facebook.com/intern/diff/D33368186)

### CODE REVIEW

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Review by ejguan — APPROVED** [review]

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Comment by NivekT** [comment]
@nivekt has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D33368186).

**Pull request closed without merging**
